apiVersion: v1
kind: Service
metadata:
  name: openfooddiary
  namespace: {{ .Release.Namespace }}
  labels:
    app: openfooddiary
spec:
  ports:
    - name: http
      port: 3012
      protocol: TCP
      targetPort: web
  selector:
    app: openfooddiary
  type: ClusterIP
