apiVersion: v1
kind: Secret
metadata:
  name: openfooddiary-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cassandrauser: {{ required "cassandra.user is required" .Values.cassandra.user | b64enc }}
  cassandrapassword: {{ required "cassandra.password is required" .Values.cassandra.password | b64enc }}
