apiVersion: v1
kind: Service
metadata:
  name: openfooddiary
  namespace: {{ .Release.Namespace }}
  labels:
    app: openfooddiary
spec:
  ports:
  - name: http
    port: 3012
    protocol: TCP
    targetPort: 3012
  selector:
    app: openfooddiary
  type: ClusterIP