env:
  es2021: true
  node: true
  browser: true
  jest/globals: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
overrides:
  - files: ['*.svelte']
    processor: 'svelte3/svelte3'
  - files: ['*.ts']
    parser: '@typescript-eslint/parser'
settings:
  'svelte3/typescript': true
plugins:
  - 'svelte3'
  - '@typescript-eslint'
  - 'jest'
rules: 
  quotes:
    - error
    - double
  semi:
    - error
    - always
  'no-multiple-empty-lines': 
    - error 
    - { max: 2, maxEOF: 1 }