name: Publish OpenFoodDiary Container

on:
  release:
    types: [published]

jobs:
  build-and-test-webapp:
    uses: ./.github/workflows/build_and_test_webapp.yml

  build-and-test-server:
    uses: ./.github/workflows/build_and_test_server.yml

  publish:
    needs:
      - build-and-test-webapp
      - build-and-test-server
    uses: ./.github/workflows/build_docker_image.yml
    with:
      VERSION: ${{ github.event.release.tag_name }}
      PUSH: true
      PUSH_LATEST: true
