name: Publish OpenFoodDiary Container

on:
  release:
    types: [published]

jobs:
  build-and-test-webapp:
    uses: ./.github/workflows/build_and_test_webapp.yml

  build-and-test-server:
    uses: ./.github/workflows/build_and_test_server.yml

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-and-test-webapp
      - build-and-test-server
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Publish the Docker image
        working-directory: .
        run: |
          export REPOSITORY="ghcr.io/leemartin77/openfooddiary"
          export VERSION=${{ github.event.release.tag_name }}
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t "$REPOSITORY:latest" -t "$REPOSITORY:$VERSION" --push .
