name: Publish OpenFoodDiary Container

on:
  release:
    types: [published]

jobs:
  build-and-test-webapp:
    uses: ./.github/workflows/build_and_test_webapp.yml

  build-and-test-server:
    uses: ./.github/workflows/build_and_test_server.yml

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-and-test-webapp
      - build-and-test-server
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish the Container image
        working-directory: .
        run: |
          export REPOSITORY="ghcr.io/leemartin77/openfooddiary"
          export VERSION=${{ github.event.release.tag_name }}
          platarch=linux/arm/v7,linux/arm64/v8,linux/amd64
          podman build --jobs=3 --platform=$platarch --manifest "$REPOSITORY:$VERSION" .
          podman tag "$REPOSITORY:$VERSION" "$REPOSITORY:latest"
          podman push "$REPOSITORY:$VERSION"
          podman push "$REPOSITORY:latest"
